### ISSUE TITLE
IES_Tookit: Push/Pull Translucent shade elements

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/IES_Toolkit#182]
#### Description:

IES can now model translucent shading elements and initial tests suggest that these can be imported via GEM (_although the validity of the solar shading calculation of the imported geometry is TBC_) so we should develop functionality to be able to Push/Pull BHoM objects to/from GEM as translucent shade objects.

GEM format defines a translucent shade using:
```
Type = 1
Subtype = 2102
```

Relates to BHoM.Environment_oM issue: [#1334](https://github.com/BHoM/BHoM/issues/1334)

**Comment by jamesramsden-bh** [comment]
![image](https://user-images.githubusercontent.com/84443868/151348165-0ae37676-53aa-4277-9a16-9f18700088da.png)

**Comment by jamesramsden-bh** [comment]
![image](https://user-images.githubusercontent.com/84443868/151349106-e434ad1e-acd0-4a44-ace3-8ca210cd1d86.png)

**Comment by jamesramsden-bh** [comment]
![image](https://user-images.githubusercontent.com/84443868/151350592-817debfb-32f3-4287-ad93-1d49331bc474.png)

**Comment by jamesramsden-bh** [comment]
Example of versioning: 
![image](https://user-images.githubusercontent.com/84443868/151350815-13daa4f2-1fad-4912-b3f5-3bd9f23211f2.png)
Something similar will need to be added to the top of the FromIESShading, like this:
![image](https://user-images.githubusercontent.com/84443868/151350900-911ef758-7022-4ce0-8bf2-9fb928c745ee.png)

**Comment by jamesramsden-bh** [comment]
@robinflyman additional tasks to be completed as part of this issue:

1) Firstly, we should test that the changes have not broken existing functionality. We currently have a test procedure that tests pushing and pulling with the IES Toolkit. Please follow the test procedure as it currently exists - hopefully it should still pass. Report on this issue that you have followed the test procedure, and the output of this testing. 

Parts of the test procedure may be out of date (e.g. files may have moved since the procedure was last updated). Let me know if anything with the test procedure isn't quite right - we will probably need to update it. 

The testing files are here: 
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FIES%5FToolkit&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

And the test procedures are here:
https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F01%5FMaster%20File&viewpath=%2Fsites%2FBHoM%2F01%5FMaster%20File%2FForms%2FAllItems%2Easpx&viewid=1a5ff972%2Da100%2D40f9%2Db888%2Dc49620280c14&id=%2Fsites%2FBHoM%2F01%5FMaster%20File%2F09%5FQAQC%2F04%20%2D%20Testing%20Procedures%2F0005%5FEnvironment

2) We then need to test the new functionality. Currently, the test procedure does not include testing for the translucent shade. Probably the easiest solution is to create another shoebox model in IES with a translucent shade, save in GEM format, and attempt to read it in GH. You'll likely need to speak to one of our resident IES experts (including Charlie, Ross and Richard) as IES isn't a very intuitive program if you're not used to it. 

When you've done that, you'll need to then update the test procedure to include a test for pushing and pulling the functionality you've just written. 

Then finally, you'll need to do the test :)

Let me know if any problems.
