### ISSUE TITLE
IES_oM: `SurfaceIndexFragment` is effectively an adapter Id but does not implement `IAdapterId` interface

### ISSUE THREAD

**Issue by alelom** [BHoM/IES_Toolkit#214]
#### Broken rules:

The `SurfaceIndexFragment` object is effectively an adapter Id, in that it stores an external software identifier, but it does not implement the `IAdapterId` interface. Although the IES_Adapter currently does not leverage the `IAdapterId` mechanism (see #213), this object should still implement the proper interface to clarify what it is, support other features (like finding all IAdapterIds in BHoM) and allow future implementation of the IAdapterId mechanism (as discussed with @IsakNaslundBh)

#### Suggestions to restore compliance:

`SurfaceIndexFragment` needs to implement `IAdapterId`.

**Comment by FraserGreenroyd** [comment]
On review of this, I don't think it is suitable for `SurfaceIndexFragment` to implement `IAdapterId` because the property `SurfaceIndex` is not a unique identifier for that surface from IES. For example, pulling 2 spaces from IES, 2 panels from each space may share the same `SurfaceIndex` as it applies to the surfaces index in the space, which is unique to an individual space, but not unique to any individual panel.

Thus I don't think it makes sense for this object to be an `IAdapterId` and implementing the necessary properties it brings in because unique identification isn't possible.
